// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    CodeEditor: typeof import('./components/CodeEditor/src/CodeEditor.vue')['default']
    CodeMirror: typeof import('./components/CodeEditor/src/codemirror/CodeMirror.vue')['default']
    Config: typeof import('./components/Config.vue')['default']
    DeObfuscator: typeof import('./components/DeObfuscator.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Icon: typeof import('./components/Icon.vue')['default']
    Obfuscator: typeof import('./components/Obfuscator.vue')['default']
    TheLogo: typeof import('./components/TheLogo.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
  }
}

export { }
