// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    CodeEditor: typeof import('./components/CodeEditor/src/CodeEditor.vue')['default']
    CodeMirror: typeof import('./components/CodeEditor/src/codemirror/CodeMirror.vue')['default']
    Config: typeof import('./components/Config.vue')['default']
    DeObfuscator: typeof import('./components/DeObfuscator.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    Message: typeof import('./components/Message/src/message.vue')['default']
    TheLogo: typeof import('./components/TheLogo.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
  }
}

export { }
